/* Do not edit this file - it is generated by awk from a */
/* file 'vlist':  'sort vlist | awk -f vlist.awk > hc_var.h' */
/* but see makefile for more details        PJT - july 1990 */
     { "AIRTEMP ", 'R', '1' },
#define AIRTEMP   0
     { "ATTEN   ", 'I', 'A' },
#define ATTEN     1
     { "AXISAVE ", 'R', '6' },
#define AXISAVE   2
     { "AXISNUM ", 'I', '1' },
#define AXISNUM   3
     { "AXISRMS ", 'R', '6' },
#define AXISRMS   4
     { "B1      ", 'D', 'A' },
#define B1        5
     { "B2      ", 'D', 'A' },
#define B2        6
     { "B3      ", 'D', 'A' },
#define B3        7
     { "CORBIT  ", 'R', '1' },
#define CORBIT    8
     { "CORBW   ", 'R', '2' },
#define CORBW     9
     { "CORFIN  ", 'R', '4' },
#define CORFIN   10
     { "DDEC    ", 'R', '1' },
#define DDEC     11
     { "DEC     ", 'D', '1' },
#define DEC      12
     { "DEC1950 ", 'R', '1' },
#define DEC1950  13
     { "DELAY0  ", 'R', 'A' },
#define DELAY0   14
     { "DELTADEC", 'R', '1' },
#define DELTADEC 15
     { "DELTARA ", 'R', '1' },
#define DELTARA  16
     { "DEWPOINT", 'R', '1' },
#define DEWPOINT 17
     { "DRA     ", 'R', '1' },
#define DRA      18
     { "EPHFLAG ", 'A', '4' },
#define EPHFLAG  19
     { "FREQ    ", 'D', '1' },
#define FREQ     20
     { "FREQIF  ", 'R', '1' },
#define FREQIF   21
     { "ICMODE  ", 'I', '1' },
#define ICMODE   22
     { "ICOPTION", 'I', '1' },
#define ICOPTION 23
     { "INTTIME ", 'R', '1' },
#define INTTIME  24
     { "ISCHAN  ", 'I', 'S' },
#define ISCHAN   25
     { "IVALUED ", 'I', 'A' },
#define IVALUED  26
     { "LO      ", 'D', '1' },
#define LO       27
     { "LO2     ", 'R', '1' },
#define LO2      28
     { "NSCHAN  ", 'I', 'S' },
#define NSCHAN   29
     { "NSPECT  ", 'I', '1' },
#define NSPECT   30
     { "NUMCHAN ", 'I', '1' },
#define NUMCHAN  31
     { "OBSLINE ", 'A', '8' },
#define OBSLINE  32
     { "PHASELO1", 'R', 'A' },
#define PHASELO1 33
     { "PHASELO2", 'R', 'A' },
#define PHASELO2 34
     { "PHASEM1 ", 'R', 'A' },
#define PHASEM1  35
     { "PLANGLE ", 'R', '1' },
#define PLANGLE  36
     { "PLMAJ   ", 'R', '1' },
#define PLMAJ    37
     { "PLMIN   ", 'R', '1' },
#define PLMIN    38
     { "PLTB    ", 'R', '1' },
#define PLTB     39
     { "PRECIPMM", 'R', '1' },
#define PRECIPMM 40
     { "RA      ", 'D', '1' },
#define RA       41
     { "RA1950  ", 'R', '1' },
#define RA1950   42
     { "RELHUMID", 'R', '1' },
#define RELHUMID 43
     { "RESTFREQ", 'D', 'S' },
#define RESTFREQ 44
     { "SDF     ", 'R', 'S' },
#define SDF      45
     { "SFREQ   ", 'R', 'S' },
#define SFREQ    46
     { "SOURCE  ", 'A', '8' },
#define SOURCE   47
     { "SYSTEMP1", 'R', 'A' },
#define SYSTEMP1 48
     { "SYSTEMP2", 'R', 'A' },
#define SYSTEMP2 49
     { "SYSTEMP3", 'R', 'A' },
#define SYSTEMP3 50
     { "SYSTEMP4", 'R', 'A' },
#define SYSTEMP4 51
     { "SYSTEMP5", 'R', 'A' },
#define SYSTEMP5 52
     { "SYSTEMP6", 'R', 'A' },
#define SYSTEMP6 53
     { "SYSTEMP7", 'R', 'A' },
#define SYSTEMP7 54
     { "SYSTEMP8", 'R', 'A' },
#define SYSTEMP8 55
     { "TEMPS1  ", 'R', 'A' },
#define TEMPS1   56
     { "TEMPS2  ", 'R', 'A' },
#define TEMPS2   57
     { "TEMPS3  ", 'R', 'A' },
#define TEMPS3   58
     { "TEMPS4  ", 'R', 'A' },
#define TEMPS4   59
     { "TEMPS5  ", 'R', 'A' },
#define TEMPS5   60
     { "TEMPS6  ", 'R', 'A' },
#define TEMPS6   61
     { "TEMPS7  ", 'R', 'A' },
#define TEMPS7   62
     { "TEMPS8  ", 'R', 'A' },
#define TEMPS8   63
     { "TPWR    ", 'R', 'A' },
#define TPWR     64
     { "VELDOP  ", 'R', '1' },
#define VELDOP   65
     { "VELOC   ", 'R', '1' },
#define VELOC    66
     { "VSUBIO  ", 'R', 'A' },
#define VSUBIO   67
     { "WFREQ   ", 'R', '2' },
#define WFREQ    68
     { "WINDDIR ", 'A', '4' },
#define WINDDIR  69
     { "WINDMPH ", 'R', '1' },
#define WINDMPH  70
#define MAXVAR 71
