BEGIN {
    printf("/* Do not edit this file - it is generated by awk from a */\n");
    printf("/* file 'vlist':  'sort vlist | awk -f vlist.awk > hc_var.h' */\n");
    printf("/* but see makefile for more details        PJT - july 1990 */\n");
}

{
    printf( "     { \"%-8s\", '%1s', '%1s' },\n", $1, $2, $3 ) ;
    printf( "#define %-8s %2d\n", $1, a++ ) ;
}

END {
    print "#define MAXVAR", a ;
    }
