#! /bin/csh -f
#  
#


set ftp=http://carma.astro.umd.edu/data
#set ftp=ftp://ftp.astro.umd.edu:/pub/carma/data
set tar=c0104I.8D_115NGC4254.2.miriad.tar.gz
set tar2=ngc4254.cmnorm.ref.tar.gz

foreach arg ($*)
  set $arg
end


set file=$ftp/$tar
set file2=$ftp/$tar2


which wget >& /dev/null
if ($status) then
  which curl >& /dev/null
  if ($status) then
    echo Cannot use wget or curl to fetch $file, go grab it yourself
    exit 1
  else
    curl $file  | tar zxf -
    curl $file2 | tar zxf -
  endif
else
  wget -O - $file  | tar zxf -
  wget -O - $file2 | tar zxf -
endif

set vis=$tar:r:r

echo $file has been downloaded
echo Local miriad dataset is now $vis
itemize in=$vis



