%% This file is to be included by latex by various miriad ??.tex files
%
% Standard disclaimer, copright etc. notices. They go on inside cover page
% ------------------------------------------------------------------------
%  History:
%   pjt 
%   mjs 02apr91 Changed "Miriad" to MIRIAD, altered "Restrictions" section
% ------------------------------------------------------------------------

% no heading, pagenumbers; change to smaller Roman (?) font
\pagestyle{empty}
\tiny
\rm

\section*{MIRIAD Description}

MIRIAD (Multichannel Image Reconstruction, Image Analysis, and
Display) is a software package available on Sun Workstations, VAX/VMS,
and Cray/UNICOS systems.  It is intended that astronomers will be able to
use MIRIAD to easily reconstruct, analyze, and display their data
without having an in-depth programmer's knowledge of the system on
which MIRIAD resides.

\section*{Restrictions on Use}

MIRIAD is copyright by the Berkeley-Illinois-Maryland Association (BIMA)
Project.  All portions of MIRIAD, including source code, may be used
subject only to the following restrictions:  (1) unmodified MIRIAD may
be distributed freely on-site and may allow unrestricted access worldwide;
(2) modified MIRIAD must clearly note its non-standard nature and that
portion derived from MIRIAD cannot be claimed as proprietary;
(3) distribution of MIRIAD requires formal notification to one of the
MIRIAD contacts listed below; (4) receipt of MIRIAD binds all recipients
to the above three restrictions and to all restrictions on portions of
MIRIAD not developed by BIMA (especially PGPLOT).

\section*{Disclaimer}
We give no warranty, expressed or implied, for the software and/or
documentation provided, including, without limitation, warranty
of merchantibility and warranty of fitness for a particular purpose.

\section*{Trademark Acknowledgments}
UNIX is a registered trademark of AT\&T.
CRAY and UNICOS are registered trademarks of Cray Research Inc.
Sun is a registered trademark and Sun Workstation a trademark of Sun
Microsystems Inc.
VAX and VMS are registered trademarks of Digital Equipment Corporation.
PGPLOT is copyright by the California Institute of Technology (all
rights reserved).
LINPACK is courtesy of SIAM.

\section*{MIRIAD Contacts}
Please address all communication concerning MIRIAD to one of
the addresses below: 

MIRIAD                                  \newline
Radio Astronomy Lab                     \newline
University of California                \newline
Berkeley, California  94720             \newline
INTERNET:  mirth@bkyast.berkeley.edu    \newline


MIRIAD                                  \newline
Astronomy Department                    \newline
Astronomy Building                      \newline
1002 West Green Street                  \newline
Urbana, Illinois  61801                 \newline
INTERNET:  miriad@sirius.astro.uiuc.edu \newline


MIRIAD                                  \newline
Laboratory for Millimeter Astronomy     \newline
Astronomy Program                       \newline
University of Maryland                  \newline
College Park, MD  20742                 \newline
INTERNET:  mirth@astro.umd.edu          \newline

% set back to normal Roman font
\rm
\normalsize
