#! /bin/csh -f
#
#  BIMA was at :    -121:28:18.49   40:49:02.50
#  this adds two uv variables to please the more carma centric version of listobs

set vis=$1

puthd in=$vis/latitud type=double value=0.7123973434
puthd in=$vis/longitu type=double value=4.1631024004
