#!/bin/sh

prefix=$MIR
exec_prefix=${prefix}
exec_prefix_set=no

usage="\
Usage: mir-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--libs] [--cflags]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 1.0.0
      ;;
    --cflags)
      includes="-I${MIRINC} -I${MIRSUBS}"
      echo $includes
      ;;
    --libs|--static-libs)
      #libdirs="-L${MIRLIB} -Wl,-rpath,${MIRLIB}"
      libdirs="-L${MIRLIB}"
      echo "$libdirs -L/usr/X11R6/lib -lmir -llinpack -lpgplot -lX11 -lm"
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
