#!/bin/csh -f

#  This is a shell script to build the Miriad programmers guide. NOTE that it
#  uses the index utility -- which converts a .idx file into a .ind file

# Generate the appendix on installation notes.

if ( -e $MIR/README ) cp $MIR/README .
unset noclobber
echo "{\small\begin{verbatim}"		>  install.inc
detab README				>> install.inc
echo "\end{verbatim}}"			>> install.inc

# Get the appendices on uvvariables and image items.

cp ../user/latexdefs.inc defs.inc
cp ../user/{uvvars,image}.inc .

# Run Latex a few times to get the page numbers right.

Buildtitlepage
latex progguide
latex progguide
latex progguide

# Generate the index and the final dvi file.

makeindex progguide.idx
latex progguide

# Generate the postscript file.

dvips -o progguide.ps progguide
cp progguide.ps junk.ps
compress junk.ps
mv junk.ps.Z progguide.ps.Z
cp progguide.ps junk.ps
gzip -best junk.ps
mv junk.ps.gz progguide.ps.gz

dvips -tletter -y940 -o progguide_US.ps progguide
cp progguide_US.ps junk.ps
compress junk.ps
mv junk.ps.Z progguide_US.ps.Z
cp progguide_US.ps junk.ps
gzip -best junk.ps
mv junk.ps.gz progguide_US.ps.gz

# Delete the things we get from elsewhere, so we are not tempted to modify
# them

rm install.inc uvvars.inc image.inc README defs.inc
