c Warning: do not edit this file, it has possibly been generated by configure
c TELESCOPE=sma
c 2006-5-19 jhz increases MAXCHAN.
c=======================================================================
	INTEGER   MAXBUF
	PARAMETER(MAXBUF=4194304)
c
	INTEGER   MAXDIM, MAXDIM2
	PARAMETER(MAXDIM=4096,MAXDIM2=8192)
c
	INTEGER   MAXIANT,MAXANT,MAXANT2
	PARAMETER(MAXIANT=256,MAXANT=30,MAXANT2=28)
c		maximum number of baselines
	INTEGER   MAXBASE
	PARAMETER(MAXBASE=((MAXANT*(MAXANT+1))/2))
c       why in the miriad configure maxdim.h specify
c       MAXBASE=435???, which cause some trouble to
c       smablflag and blflag.
c	PARAMETER(MAXBASE=435)
	INTEGER   MAXBASE2
	PARAMETER(MAXBASE2=500)
c
	INTEGER   MAXCHAN
        PARAMETER(MAXCHAN=8217)
c	PARAMETER(MAXCHAN=7681)
c
	INTEGER   MAXWIN
	PARAMETER(MAXWIN=48)
c
	INTEGER   MAXWIDE
	PARAMETER(MAXWIDE=18)
c=======================================================================

