.TH dtm_version 3DTM "7 July 1992" DTM "DTM Version 2.0"
.SH "NAME"
\fBdtm_version\fP - Print the current version of DTM.
.SH "SYNOPSIS"
.nf
\fB#include <dtm.h>\fP
.LP
\fBvoid dtm_version(void )\fP
.SH "DESCRIPTION"
.nf
\fBdtm_version\fP prints the current version of the DTM library to \fIstderr\fP.
