.TH SDLsetClass 3DTM "7 February 1992" DTM "DTM Version 2.0"
.LP
.SH "NAME"
.B SDLsetClass, SDLcompareClass - 
Surface description language class labeling and scanning macros.
.LP
.SH "SYNOPSIS"
.nf
.B #include <sdl.h>
.LP
.B SDLsetClass(char *\fIheader\fP)
.LP
.B SDLcompareClass(char *\fIheader\fP)
.fi
.LP
.SH "DESCRIPTION"
.B SDLsetClass
inserts the message class constant 
.B SDLclass
into the character string
.I header
indicating that the data to follow should be considered surface
description language information.  The 
.B SDLclass
constant is declared in the 
file 
.I sdl.h,
and though it is accessible at all times, it is recommended that
the macro 
.B SDLsetClass
be used to correctly insert this message type tag into the header.
.LP
.B SDLcompareClass
returns a non-zero value if the character string
.I header
contains the 
.B SDLclass
constant.  Though the constant 
.B SDLclass
is accessible at all times, it is 
recommended that the macro 
.B SDLcompareClass
to determine whether or not a header
indicates surface description data.
.LP
.SH "SEE ALSO"
DTM, SDLclass
.LP
.SH "BUGS"
.B SDLsetClass
has no way of determining if the header contains sufficient space to 
hold the tag 
.B SDLclass.
The results of attempting to store this
information beyond the end of the allocated space are undefined.
