%\nonstopmode
%\input{htmldefs.inc}
%\newcommand{\oneliner}[1]{\begin{flushleft}{\ \ \ #1}\end{flushleft}}
%\documentstyle[twoside,makeidx,html,epsf]{report}
%\setlength{\parindent}{0pt}
%\setlength{\parskip}{2.5mm}
%\setlength{\textheight}{245mm}
%\setlength{\textwidth}{160mm}
%\setlength{\oddsidemargin}{10mm}
%\setlength{\evensidemargin}{-10mm}
%\setlength{\topmargin}{-10mm}
%\begin{document}

\chapter{Bibliography}



Bracewell R.N., The Fourier Transform and its Applications

Briggs D., 1995, \htmladdnormallink{``High fidelity deconvolution of moderately resolved sources''}
{http://www.aoc.nrao.edu/dissertations/dbriggs/}
PhD thesis
\begin{latexonly}
\\ \verb+http://www.aoc.nrao.edu/dissertations/dbriggs/+
\end{latexonly}.

Christiansen W.N., H\"ogbom J.A., Radiotelescopes.

Clark B.G., 1980, \htmladdnormallink{``An efficient implementation of the algorithm CLEAN''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1980A\%26A....89..377C}
{\it Astron. Astrophys.} 26, 89.

Cornwell T.J., 1983, \htmladdnormallink{``A method of stabilizing the clean algorithm''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1983A\%26A...121..281C}
{\it Astron. Astrophys.}, 121, 281.

Cornwell T.J., 1988
\htmladdnormallink{``Radio-interferometric imaging of very large objects''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1988A\%26A...202..316C}
{\it Astron. Astrophys.}, 202, 316.

Cornwell T.J., Holdaway M.A., Uson J.M., 1993
\htmladdnormallink{``Radio-interferometric imaging of very large objects: implications for array design''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1993A\%26A...271..697C}
{\it Astron. Astrophys.}, 271, 697.

Cornwell T.J., Uson J.M., Haddad N., 1992, \htmladdnormallink{``Radio-interferometric imaging of spectral lines - The problem of continuum subtraction''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1992A\%26A...258..583C}
{\it Astron. Astrophys.}, 258, 583.

Frater R.H. ed., 1992,
Journal of Electrical and Electronics Engineering, Australia: 
\htmladdnormallink{Special
Issue -- The Australia Telescope}{http://www.narrabri.atnf.csiro.au/observing/iree.pdf}, 12
\begin{latexonly}
\\ \verb+http://www.narrabri.atnf.csiro.au/observing/iree.pdf+
\end{latexonly}.

Greisen E., 1993, \htmladdnormallink{``{\it Non-linear coordinate systems in \aips}''}
{ftp://ftp.aoc.nrao.edu/pub/software/aips/TEXT/PUBL/AIPSMEMO27.PS}
\aips\ memo No. 27
\begin{latexonly}
\\ \verb+ftp://ftp.aoc.nrao.edu/pub/software/aips/TEXT/PUBL/AIPSMEMO27.PS+
\end{latexonly}.

Hamaker J.P., Bregman J.D., Sault R.J., 1996,
\htmladdnormallink{``Understanding radio polarimetry. I. Mathematical foundations''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1996A\%26AS..117..137H}
{\it Astron. Astrophys.} 117, 137.

H\"ogbom J.A., 1974, \htmladdnormallink{``Aperture Synthesis with a Non-Regular Distribution of Interferometer Baselines''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1974A\%26AS...15..417H}
{\it Astron. Astrophys. Suppl.} 15, 417.

Killeen N.E.B., 1996, 
\htmladdnormallink{``Effective spectral resolution of the ATNF correlator''}
{http://www.atnf.csiro.au/observers/memos/d98b8b\~{}1.pdf} AT Memo 39.3/057
\begin{latexonly}
\\ \verb+http://www.atnf.csiro.au/observers/memos/+
\end{latexonly}.

Killeen N.E.B., Lo K.Y., Crutcher R., 1992,
\htmladdnormallink{``Zeeman measurements of the magnetic fields at the Galactic center''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1992ApJ...385..585K}
{\it Astrophys. J.}, 385, 585.

Kraus J.D., Radio Astronomy

Rayner, D. 2000, \htmladdnormallink{``Circular polarization users guide''}
{http://www.atnf.csiro.au/observers/memos/circpolguide.pdf}, AT Memo 39.3/102
\begin{latexonly}
\\ \verb+http://www.atnf.csiro.au/observers/memos/+
\end{latexonly}.

Reynolds J.E., 1994, 
\htmladdnormallink{``A revised flux scale for the AT
Compact Array''}{http://www.atnf.csiro.au/observers/memos/d96783\~{}1.pdf}
AT Memo 39.3/040
\begin{latexonly}
\\ \verb+http://www.atnf.csiro.au/observers/memos/+
\end{latexonly}.

Rohlfs K., Wilson T.L., Tools of Radio Astronomy.

Sault R.J., 1991, \htmladdnormallink{``Some simulations of
self-calibration for the AT''}
{http://www.atnf.csiro.au/observers/memos/d96f87~{}1.pdf} AT Memo 39.3/058
\begin{latexonly}
\\ \verb+http://www.atnf.csiro.au/observers/memos/+
\end{latexonly}.

Sault R.J., 1994, \htmladdnormallink{``An analysis of visibility-based continuum subtraction''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1994A\%26AS..107...55S}
{\it Astron. Astrophys. Suppl.}, 107, 55.

Sault R.J., 2003,
\htmladdnormallink{``ATCA flux density scale at 12mm''}
{http://www.atnf.csiro.au/observers/memos/AT39.3_124.pdf} AT Memo 39.3/124
\begin{latexonly}
\\ \verb+http://www.atnf.csiro.au/observers/memos/+
\end{latexonly}.

Sault R.J., Bock D.C.-J., Duncan A.R., 1999,
\htmladdnormallink{``Polarimetric imaging of large fields in radio astronomy''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1999A\%26AS..139..387S}  
{\it Astron Astrophys. Suppl.}, 139, 387.

Sault R.J., Killeen N.E.B., Zmuidzinas J., Loushin R., 1990,
\htmladdnormallink{``Analysis of Zeeman effect data in radio astronomy''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1990ApJS...74..437S}
{\it Astrophys. J. Suppl.}, 74, 437.

Sault R.J., Killeen N.E.B., Kesteven, M.J., 1991
\htmladdnormallink{``AT Polarisation Calibration''}
{http://www.atnf.csiro.au/observers/memos/d97b7f\~{}1.pdf} AT Memo 39.3/015
\begin{latexonly}
\\ \verb+http://www.atnf.csiro.au/observers/memos/+
\end{latexonly}.

Sault R.J., Hamaker J.P., Bregman J.D., 1996,
\htmladdnormallink{``Understanding radio polarimetry. II. Instrumental calibration of an interferometer array''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1996A\%26AS..117..149S}
{\it Astron. Astrophys.}, 117, 149.

Sault R.J., Noordam J.E., 1995, 
\htmladdnormallink{``Eliminating solar interference in radio interferometric spectrometry''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1995A\%26AS..109..593S}
{\it Astron. Astrophys. Suppl.}, 109, 539.

Sault R.J., Staveley-Smith L., Brouw W.N., 1996,
\htmladdnormallink{``An approach to interferometric mosaicing''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1996A\%26AS..120..375S}
{\it Astron. \& Astrophys. Suppl.}, 120, 376.

Sault R.J., Teuben P.J.,
Wright M.C.H., 1995, \htmladdnormallink{``A retrospective view of Miriad''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1995ASPC...77..433S}
in {\it Astronomical Data Analysis Software and
Systems IV},
ed. R. Shaw, H.E. Payne, J.J.E. Hayes, ASP Conf. Ser., 77, 433-436.

Sault R.J., Wieringa M.H., 1994, \htmladdnormallink{``Multi-frequency synthesis techniques in radio interferometric imaging''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1994A\%26AS..108..585S}
{\it Astron. Astrophys. Suppl.}, 108, 585.

Stanimirovic S., 2002, 
\htmladdnormallink{``Short-Spacings Correction from the Single-Dish Perspective''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=2002sdra.conf..375S}   
ASP Conf. Series, 278, p 375.

Steer D.G., Dewdney P.E., Ito M.R., 1984, \htmladdnormallink{``Enhancements to the deconvolution 
algorithm CLEAN''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1984A\%26A...137..159S}
{\it Astron. Astrophys.}, 137, 159

Subrahmanyan R., 2005,
\htmladdnormallink{``Photogrammetric measurement of the gravity deformation
in a Cassegrain antenna''}
{http://ieeexplore.ieee.org/iel5/8/32084/01492610.pdf?tp=&arnumber=1492610&isnumber=32084}
{\it IEEE Trans Antennas Propogation}, 53, 2590-2596.

Taylor G.B., Carilli C.L., Perley R., eds,
Synthesis Imaging in Radio Astronomy II,
Astronomical Society of the Pacific Conference Series Volume 180.

Thompson A.R., Moran J.M., Swenson G.W., Interferometry and Synthesis in Radio Astronomy.

Ulich B.L.\ 1980, \htmladdnormallink{``Improved correction for millimeter-wavelength atmospheric attenuation''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1980ApL....21...21U},
{\it Astrophys. Letters}, 21, 21.

van Hoerner S., 1967, 
\htmladdnormallink{``Design of large steerable antennas''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1967AJ.....72...35V}
{\it Astron. J.}, 72, 35.

Wieringa M.H., Kesteven M.J, 1992, \htmladdnormallink{``Measurements of the ATCA primary beam''}
{http://www.atnf.csiro.au/observers/memos/d97f7b\~{}1.pdf}, AT Memo 39.3/024
\begin{latexonly}
\\ \verb+http://www.atnf.csiro.au/observers/memos/+
\end{latexonly}.

%\end{document}
