#!/bin/csh -f

#  This is a shell script to build the Miriad users guide.

# Generate the title page

Buildtitlepage

# Generate the figures (from .fig files)

Buildfigs

# Run LaTeX three times to make sure we have the page numbering right.

latex userguide
latex userguide
latex userguide

# Generate the index and the final dvi file.

makeindex userguide.idx
latex userguide

# Generate the postscript file.

dvips -o userguide.ps userguide
cp userguide.ps junk.ps
gzip junk.ps
mv junk.ps.gz userguide.ps.gz

dvips -tletter -y940 -o userguide_US.ps userguide
cp userguide_US.ps junk.ps
gzip junk.ps
mv junk.ps.gz userguide_US.ps.gz
