#!/bin/csh -f
# Convert the doc files to man

set out = $MIR/man/man1

echo "***************** Converting .doc files to man files."
foreach file ($MIRPDOC/*.doc)
  set tmp = $file:t
  set tmp = $tmp:r
  if ( ! -e $MIR/specdoc/$tmp.doc ) then
    doc2man $file > $tmp.1
    mv $tmp.1 $out  
  endif
end

catman -M $MIR/man -w
