#!/bin/csh
rm -f /tmp/$$.{1,2} tasks.doc
foreach file ( $MIRPDOC/*.doc )
  set tail = $file:t
  set tail = $tail:r
  if ( -e $MIRBIN/$tail ) then
    echo $tail >> /tmp/$$.1
  else
    echo $tail >> /tmp/$$.2
  endif
end
echo "%D A list of Miriad tasks"	>> tasks.doc
echo "%: miscellaneous"			>> tasks.doc
echo "%B"				>> tasks.doc
echo "	Available Miriad tasks are given below." >> tasks.doc
echo "	Type"				>> tasks.doc
echo "	  help <taskname>"		>> tasks.doc
echo "	to get extra help."		>> tasks.doc
echo " "				>> tasks.doc
pr -6 -l1 -t /tmp/$$.1 >> tasks.doc
echo " "				>> tasks.doc
echo "	Other help topics available are">> tasks.doc
echo " "				>> tasks.doc
pr -6 -l1 -t /tmp/$$.2 >> tasks.doc

