\bodytext{background=hmiriad.gif}
\newcommand{\task}[1]{\htmladdnormallink{#1}{#1.html}}
\newcommand{\unix}[1]{\htmladdnormallink{#1}{/cgi-bin/miriad/mirman.pl?topic=#1}}
\newcommand{\miriad}{{\it Miriad}}
\newcommand{\aips}{AIPS}
\newcommand{\MM}[1]{{\it #1}}
\newcommand{\TT}[2]{{#1 by #2}}
\newcommand{\degrees}{\ degrees}
\newcommand{\kms}{km/s}
\newcommand{\radm}{rad/m/m}
\newcommand{\newchapter}{\null}
\newcommand{\lookat}{See}
\newcommand{\elll}{l}
\newcommand{\ssigma}{sigma}
