#! /bin/csh -f
#


set version=$MIR:t

echo Updating $MIR with UMD patches for version $version

cp MIRRC.local MIRSRC.local     $MIR
cp Makefile                     $MIRLIB
#cp mirlibs  mirsao mirtng       $MIRBIN
cp mirlibs                      $MIRBIN
cp mir.man                      $MIRBIN

cat MIRSRC.linux |\
  sed s,/appl/lai/miriad/mirdir,$MIRTEMP, |\
  sed s,yymmmdd,$version, >! $MIR/MIRSRC.linux


#    works on mandrake8, but fails on redhat 7.1
if (1) then
  echo Keeping log in $MIR/tmp/mir.genman.log
  mir.genman -n >& $MIR/tmp/mir.genman.log
else
  echo Skipping mir.genman for now
endif


