#! /bin/csh -f
#
# bla bla

set version=$MIR:t

echo Updating $MIR with UMD patches for version $version

cp MIRRC.local MIRSRC.local     $MIR
cp Makefile                     $MIRLIB
#cp mirlibs  mirsao mirtng      $MIRBIN
cp mirlibs                      $MIRBIN
cp mir.man                      $MIRBIN

#    works on mandrake8, but fails on redhat 7.1 - seems ok on redhat 7.3
if (1) then
  echo Keeping log in $MIR/tmp/mir.genman.log
  echo Sometimes this program can hang on linux man page updates.....
  ./mir.genman -n >& $MIR/tmp/mir.genman.log &
else
  echo Skipping mir.genman for now
endif


#  $MIR/opt is now in CVS, but it needs symlinks to support --prefix installs here
set opt=$MIR/opt
cd $opt
ln -s ../bin/$MIRHOST bin
ln -s ../lib/$MIRHOST lib
ln -s ../inc          include


