#! /bin/csh -f
#
#  Install the JPL line catalog in $MIRCAT
#  Clients that can use this are:
#   1) (sma)miriad's program SmaUvSpec
# 
#   2)  nemo's program  tabpp      (needs PP_DIR set to $MIRCAT/jplcat)
#       http://bima.astro.umd.edu/nemo/man_html/tabpp.1.html
#      
#
#  See also (node #'s might change)
#      http://sma-www.cfa.harvard.edu/miriadWWW/manuals/SMAuguide/smauserhtml/node84.html
#      http://sma-www.cfa.harvard.edu/miriadWWW/manuals/SMAuguide/smauserhtml/node14.html

set mode=1

set url=http://sma-www.cfa.harvard.edu/miriadWWW/smaspec/catalog/jplcatalog.tar.gz


cd $MIRCAT
if (-e jplcat) then
  echo Warning: existing directory $MIRCAT/jplcat will be filled again
endif

if ($mode == 1) then
  curl $url | tar zxf -
else if ($mode = 2) then
  wget $url
  tar zxf $url:t
  rm $url:t
else
  echo mode $mode not supported
endif
