#! /bin/csh -f 
#
#  this script will generate new miriad_start.{csh,sh} files
#

if ($#argv == 0) then
  # try and discover, if the current directory looks like a miriad one
  if (-e MIR4 && -d borrow) then
    echo Testing
    set m=`pwd`
    set ht=(`echo MIRRC.* | sed s/MIRRC.local// | sed s/MIRRC.//`)
    if ($#ht == 1) then
      echo Found MIR=$m hosttype=$ht
      set MIR=$m
      set hosttype=$ht
    else
      echo Current directory does not look like a MIR4 root directory
      exit 1
    endif
  endif
else if ($#argv == 2) then
  set MIR=$1
  set hosttype=$2
endif

if ($#argv != 2) then
  echo Usage: $0 MIR hosttype
  exit 1
endif





if (! -e $MIR/MIR4) then
  echo Warning: $MIR/MIR4 did not exist
  exit 1
endif

echo make_miriad_starts: using MIR=$MIR

cd $MIR

set start1=miriad_start.csh
echo "# source this file to set MIR env"  > $start1
echo "setenv MIR $MIR"                   >> $start1
echo 'source $MIR/MIRRC'."$hosttype"     >> $start1
echo "# this script was created by $0"   >> $start1

set start2=miriad_start.sh
echo "# source this file to set MIR env"  > $start2
echo "export MIR=$MIR"                   >> $start2
echo 'source $MIR/MIRSRC'."$hosttype"    >> $start2
echo "# this script was created by $0"   >> $start2
