% -*- TeX -*-

\section{Future}

As we begin to understand the complexity of the combined BIMA/OVRO array, 

\begin{itemize}
\item
Polarization
\item
Blanking and Flagging: baseline and band dependant integration times.
\item
More detailed primary beam models for OVRO and BIMA for improved mosaicing. Currently
only simple gaussians are used.
\item
Iterative Selfcal (cf. BIMA Song scripts)
\end{itemize}



