% -*- TeX -*-

\section{Future}

As we begin to understand the complexity of the combined BIMA/OVRO array, and
get calibration under control, a number of new techniques will undoubtedly
will have to be addressed. We name a few that are coming on the horizon:

\begin{itemize}
\item
Polarization
\item
Blanking and Flagging: baseline and band dependant integration times. This will
require some changes to the lower level Miriad code.
\item
More detailed primary beam models for OVRO and BIMA for improved mosaicing. Currently
only simple gaussians are used. Again something needed in Miriad.
\item
Iterative Selfcal (cf. BIMA Song scripts)
\end{itemize}



