% -*- TeX -*-


\chapter{Introduction}

\begin{latexonly}
This manual is also available, in hypertext form, on the World
Wide Web at 
\begin{verse}
{\verb+http://bima.astro.umd.edu/miriad+}
\end{verse}
% This also contains information on retrieving and installing \miriad.
\end{latexonly}

This manual serves as a cook book for CARMA data using the
\miriad\ package. It is assumed that the reader has some familiarity
with the underlying {\bf Unix} operating system (be it Linux, Solaris or Darwin)
and \miriad\ itself. 


\section{Users Guide}

All general information, and many procedures also relevant for Carma, can be obtained
from two existing Users Guide's:

\subsection{Miriad Users Guide}

Throughout the cookbook  the reader is assumed to be
familiar with the MIRIAD Users Guide, in particular
Chapters 2 (the Miriad shell), 3 (plotting and the {\tt device=} keyword), 4 (what miriad datasets
really are). Chapter 5 on visibility data is in particular important, if deals with
the different types of {\it calibration tables}, and the {\tt select=} keyword. Chapter 6
on image data is much shorter but also important to read. Chapter 10 on flagging
is also important.

\subsection{SMA Users Guide}

The recently written SMA Users Guide contains lots of useful information as well,
in a cookbook style, which can be complementary to the current cookbook and
the Miriad Users Guide.

\section{Future}

This cookbook is a currently a live document, it will change radidly over the coming
months. Also be sure to be subscribed to the relevant mailing lists:
{\tt miriad-dev} for Miriad development issues, {\tt carma-obs} for Carma observatory.
Miriad data versions (the filler changes from time to time). Developments around
flagging and blanking, baseline and band depending integration times, polarization etc.. 
Our {\bf bugzilla} has an module for miriad as well, though again, this is probably
only useful for developers (though the developers should maintain a list of active
bugs on a more user friendly webpage).
\bigskip
A Wiki page has also been set up at {\tt http://bima.astro.umd.edu/wiki/index.php/Miriad\_Party}.

\section*{Acknowledgements}

Stuart Vogel, Stephen White, Jin Koda, Joanna Brown  etc..  
And the fine crew of the first Miriad ``Party'' where
much of this material was first fine tuned.


