
\newcommand{\newchapter}{
  \cleardoublepage
  \renewcommand{\thepage}{\thechapter-\arabic{page}}
  \setcounter{page}{1}}

\newcommand{\miriad}{{\bf $\cal MIRIAD$}}
\newcommand{\aips}{{\bf $\cal AIPS$}}
\newcommand{\task}[1]{{\tt #1}\index{#1}}
\newcommand{\unix}[1]{{\tt #1}\index{#1}}
\newcommand{\MM}[1]{$#1$}
\newcommand{\TT}[2]{{$#1\times#2$}}
\newcommand{\degrees}{$^\circ$}
\newcommand{\kms}{km~s$^{-1}$}
\newcommand{\radm}{rad~m$^{-2}$}
\newcommand{\lookat}{$\Rightarrow$}
\newcommand{\elll}{\ell}
\newcommand{\ssigma}{$\sigma$}
